
import os
import re

def fix_italics(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # Logic: Inside verbatim blocks, replace \textit{...} with _..._
    # Because _ was interpreted as italics start/end.
    
    parts = re.split(r'(\\begin\{verbatim\}.*?\\end\{verbatim\})', content, flags=re.DOTALL)
    
    new_parts = []
    for part in parts:
        if part.startswith(r'\begin{verbatim}'):
            # Inside verbatim
            # Regex to find \textit{...}
            # We assume no nested braces for simplicity (code usually doesn't have nested \textit generated by markdown)
            # Pattern: \textit{ content }
            # We want to replace with: _ content _
            
            # Use a loop to handle multiple occurrences
            # re.sub(r'\\textit\{([^}]*)\}', r'_\1_', part)
            
            # Check for \textit
            fixed_part = re.sub(r'\\textit\{([^}]*)\}', r'_\1_', part)
            
            # Also fix escaped underscores? \_ -> _ inside verbatim
            # The conversion might have escaped some.
            fixed_part = fixed_part.replace(r'\_', '_')
            
            new_parts.append(fixed_part)
        else:
            new_parts.append(part)
            
    content = "".join(new_parts)
    
    if content != original:
        print(f"Fixed italics corruption in {file_path}")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

def main():
    root_dir = r"c:\Users\SOHAN\.gemini\antigravity\playground\nascent-zodiac\papers"
    subdirs = ["A1", "A2", "A3", "A4", "A5", "A6", "AECP", "ARCH"]
    
    for subd in subdirs:
        path = os.path.join(root_dir, subd, "main.tex")
        if os.path.exists(path):
            fix_italics(path)

if __name__ == "__main__":
    main()
